language: node_js
node_js:
  - "8"
sudo: true
before_script:
  - node --version
  - npm --version
  - npm install
script:
  - npm test
os:
  - linux
cache:
  directories:
  - node_modules
addons:
  firefox: latest
  chrome: stable
